server:
  port: 8090
spring:
  application:
    name: "Authentication-Service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8090/.well-known/jwks.json"
logging:
  level:
    com.creditya.authservice: trace
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "auth_db"
    schema: "public"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
rsa:
  key:
    private-key: ${RSA_PRIVATE_KEY_PATH}
    public-key: ${RSA_PUBLIC_KEY_PATH}
