server:
  port: 8090
spring:
  application:
    name: "Authentication-Service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
logging:
  level:
    com.creditya.authservice: trace
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
rsa:
  key:
    private-key: classpath:keys/private_key.pem
    public-key: classpath:keys/public_key.pem

---
# ===============================================
# PERFIL 'default' (para desarrollo local)
# ===============================================
spring:
  config:
    activate:
      on-profile: default
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "auth_db"
    schema: "public"
    username: "postgres"
    password: "Sh4y0202597."

---
# ===============================================
# PERFIL 'docker' (para Docker Compose)
# ===============================================
spring:
  config:
    activate:
      on-profile: docker
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: "public"
    username: ${DB_USER}
    password: ${DB_PASSWORD}